sudo: false
dist: xenial
language: python
python: 3.7

cache: &global_cache
  pip: true
  directories:
    - $HOME/.local/

install:
  - sh .misc/apt_install.sh
  - sh .misc/npm_install.sh
  - sh .misc/pip3_install.sh

script:
  - sh .misc/run_test.sh
  - coala --ci
  - eclint check "**/*.{java,c,cpp}"

notifications:
  email: false
  webhooks: https://www.travisbuddy.com/
  on_success: never
